services/app/project/models.py
"""DataBase models"""
from flask_login import UserMixin  # pylint: disable=import-error
from flask_sqlalchemy.model import DefaultMeta
from . import db

BaseModel: DefaultMeta = db.Model


class User(UserMixin, BaseModel):
    """User model"""

    id = db.Column(db.Integer, primary_key=True)
    email = db.Column(db.String(100), unique=True)
    password = db.Column(db.String(100))
    name = db.Column(db.String(1000))


class UserGame(BaseModel):
    """User current game"""

    id = db.Column(db.Integer, primary_key=True)
    user_id = db.Column(db.Integer, db.ForeignKey("user.id"), nullable=False)
    level = db.Column(db.Integer)
    dificulty = db.Column(db.String(6))
    current_game = db.Column(db.String(90))
    sudoku_game = db.Column(db.String(90))

services/app/project/__init__.py
"""TODO"""
from flask import Flask
from flask.cli import FlaskGroup
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager  # pylint: disable=import-error

from .config import Config

db = SQLAlchemy()


def create_app():
    """TODO"""
    app = Flask(__name__, static_folder="../static")

    app.config.from_object(Config)
    db.init_app(app)

    login_manager = LoginManager()
    login_manager.login_view = "auth.login"
    login_manager.init_app(app)

    from .auth import auth as auth_blueprint

    app.register_blueprint(auth_blueprint)

    from .routes import routes as main_blueprint

    app.register_blueprint(main_blueprint)

    from .models import User

    @login_manager.user_loader
    def load_user(user_id):
        """Load user by user_id and not by id"""
        return User.query.get(int(user_id))

    return app

services/app/project/auth.py
"""TODO"""
from flask import Blueprint, flash, redirect, render_template, request, url_for
from flask_login import (  # pylint: disable=import-error
    login_required,
    login_user,
    logout_user,
)
from werkzeug.security import check_password_hash, generate_password_hash
from project.models import User
from . import db

auth = Blueprint(
    "auth", __name__, template_folder="../templates", static_folder="../static"
)


@auth.route("/login", methods=["GET", "POST"])
def login():
    """LogIn Page"""
    if request.method == "GET":
        return render_template("login.html")
    email = request.form.get("email")
    password = request.form.get("password")
    remember = bool(request.form.get("remember"))

    user = User.query.filter_by(email=email).first()

    if not user or not check_password_hash(user.password, password):
        flash("Please check your login details and try again.")
        return redirect(url_for("auth.login"))
    login_user(user, remember=remember)
    return redirect(url_for("main.games"))


@auth.route("/signup", methods=["GET", "POST"])
def signup():
    """SignUp Page"""
    if request.method == "GET":
        return render_template("signup.html")
    email = request.form.get("email")
    name = request.form.get("name")
    password = request.form.get("password")

    user = User.query.filter_by(email=email).first()

    if user:
        flash("Email address already exists")
        return redirect(url_for("auth.signup"))

    new_user = User(
        email=email,
        name=name,
        password=generate_password_hash(password, method="sha256"),
    )

    db.session.add(new_user)
    db.session.commit()

    return redirect(url_for("auth.login"))


@auth.route("/logout")
@login_required
def logout():
    """LogOut Page"""
    logout_user()
    return redirect(url_for("main.index"))

services/app/project/routes.py
"""Application main functionality"""
from flask import Blueprint, render_template, jsonify
from flask_login import current_user, login_required  # pylint: disable=import-error
from project.provider_requests import (
    request_sudoku_game,
    request_sudoku_valid,
    request_sudoku_complete,
)
from project.validations import is_sudoku_option
from project.models import UserGame
from . import db

routes = Blueprint("main", __name__, template_folder="../templates")


@routes.route("/")
def index():
    """application first page"""
    return render_template("index.html")


@routes.route("/games")
@login_required
def games():
    """load the select game dificulty page"""
    return render_template("games.html", name=current_user.name)


@routes.route("/sudoku/<string:dificulty>")
@login_required
def sudoku(dificulty: str):
    """loads SUDOKU board game"""
    load_game = UserGame.query.filter_by(
        user_id=current_user.id, dificulty=dificulty
    ).first()

    is_game_over = (
        request_sudoku_complete(load_game.current_game) if load_game else False
    )

    if not load_game:
        load_game = request_sudoku_game(dificulty, 0)
        if load_game.sudoku_game:
            load_game.user_id = current_user.id
            db.session.add(load_game)
            db.session.commit()
    elif is_game_over:
        new_game = request_sudoku_game(dificulty, load_game.level + 1)
        if load_game.sudoku_game:
            load_game.dificulty = new_game.dificulty
            load_game.level = new_game.level
            load_game.sudoku_game = new_game.sudoku_game
            load_game.current_game = new_game.current_game
            db.session.commit()

    return render_template(
        "sudoku.html",
        sudoku=load_game.sudoku_game,
        user_game=load_game.current_game,
        level=load_game.level,
        dificulty=dificulty,
    )


@routes.route("/sudoku/valid/move/<string:move>")
def sudoku_valid_move(move: str):
    """validate valid move (1~9)"""
    return jsonify(result=is_sudoku_option(move), move=move)


@routes.route(
    "/sudoku/move/<string:dificulty>/<int:position>/<int:move>", methods=["PUT"]
)
@routes.route(
    "/sudoku/move/<string:dificulty>/<int:position>",
    methods=["PUT"],
    defaults={"move": 0},
)
@login_required
def sudoku_move(dificulty: str, position: int, move: int):
    """TODO"""
    valid = False
    game_over = False
    load_game = UserGame.query.filter_by(
        user_id=current_user.id, dificulty=dificulty
    ).first()
    if load_game:
        list_game = list(load_game.current_game)
        list_game[position] = str(move) if move != 0 else "."
        current_game = "".join(list_game)
        valid_move = request_sudoku_valid(current_game) if move != 0 else True
        if valid_move:
            valid = True
            load_game.current_game = current_game
            game_over = request_sudoku_complete(load_game.current_game)
            db.session.add(load_game)
            db.session.commit()

    return jsonify(valid=valid, game_over=game_over)

services/app/templates/base.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="icon" href="{{url_for('static', filename='images/sudoku.ico') }}" type="image/gif" sizes="16x16">
    <title>SUDOKU</title>
    <!-- <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery-confirm/3.3.2/jquery-confirm.min.css"> -->
    <link rel="stylesheet" href="{{ url_for('static', filename='css/jquery-confirm.min.css')}}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/bulma.min.css')}}"/>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/main.css')}}"/>
    <script src="{{url_for('static', filename='js/jquery-1.10.2.min.js')}}"></script>
    <script src="{{url_for('static', filename='js/jquery-confirm.js')}}"></script>
    <script src="{{url_for('static', filename='js/sudoku.js')}}"></script>
  </head>
  <body>
    <section class="hero is-link is-fullheight">
      <div class="hero-head">
        <nav class="navbar">
          <div class="container">
            <div id="navbarMenuHeroA" class="navbar-menu">
              <div class="navbar-end">
                <a href="{{ url_for('main.index') }}" class="navbar-item">
                  Home
                </a>
                {% if current_user.is_authenticated %}
                  <a href="{{ url_for('main.games') }}" class="navbar-item">
                    Games
                  </a>
                  <a href="{{ url_for('auth.logout') }}" class="navbar-item">
                    Logout
                  </a>
                {% else %}
                  <a href="{{ url_for('auth.login') }}" class="navbar-item">
                    Login
                  </a>
                  <a href="{{ url_for('auth.signup') }}" class="navbar-item">
                    Sign Up
                  </a>
                {% endif %}
              </div>
            </div>
          </div>
        </nav>
      </div>
      <div class="hero-body">
        <div class="container has-text-centered">
          {% block content %}
          {% endblock %}
        </div>
      </div>
    </section>
  </body>
</html>

services/app/templates/games.html
{% extends "base.html" %}
{% block content %}
  <h1 class="title">
    Welcome, {{name}}! please choose your level!!
  </h1>
  <br>
  <div class="row" >
    <div class="column">
      <a href="{{ url_for('main.sudoku', dificulty='easy')}}" >
        <img alt="easy" src="{{url_for('static', filename='images/Villager-icon.png')}}">
        <p>Easy</p>
      </a>
    </div>
    <div class="column">
      <a href="{{ url_for('main.sudoku', dificulty='medium')}}">
        <img alt="medium" src="{{url_for('static', filename='images/Viking-icon.png')}}">
        <p>Medium</p>
      </a>
    </div>
    <div class="column" >
      <a href="{{ url_for('main.sudoku', dificulty='hard')}}">
        <img alt="hard" src="{{url_for('static', filename='images/Knight-icon.png')}}">
        <p>Hard</p>
      </a>
    </div>
  </div>
{% endblock %}

services/app/templates/index.html
{% extends "base.html" %}
{% block content %}
  <h1 class="title">
    SUDOKU
  </h1>
  <img src="{{url_for('static', filename='images/sudoku-art.png')}}" height="400" width="400">
  <br><br>
  <h2 class="subtitle">
    {% if current_user.is_authenticated  %}
      Go to Games to play.
    {% else %}
      Please <a href="{{url_for('auth.login')}}">Login</a>.
    {% endif %}
  </h2>
  <br>
{% endblock %}

services/app/templates/login.html
{% extends "base.html" %}

{% block content %}
  <div class="column is-4 is-offset-4">
    <h3 class="title">Login</h3>
    <div class="box">
      {% with messages = get_flashed_messages() %}
        {% if messages %}
          <div class="notification is-danger">
            {{ messages[0] }}
          </div>
        {% endif %}
      {% endwith %}
      <form method="POST" action="/login">
        <div class="field">
          <div class="control">
            <input class="input is-large" type="email" name="email" placeholder="Your Email" autofocus="">
          </div>
        </div>
        <div class="field">
          <div class="control">
            <input class="input is-large" type="password" name="password" placeholder="Your Password">
          </div>
        </div>
        <div class="field">
          <label class="checkbox">
            <input type="checkbox">
            Remember me
          </label>
        </div>
        <button class="button is-block is-info is-large is-fullwidth">Login</button>
        <br> <p> First time here? <a href="{{ url_for('auth.signup')}}">Create new User</a></p>
      </form>
    </div>
  </div>
{% endblock %}

services/app/templates/signup.html
{% extends "base.html" %}

{% block content %}
  <div class="column is-4 is-offset-4">
    <h3 class="title">Sign Up</h3>
    <div class="box">
      {% with messages = get_flashed_messages() %}
        {% if messages %}
          <div class="notification is-danger">
            {{ messages[0] }}. Go to <a href="{{ url_for('auth.login') }}">login page</a>.
          </div>
        {% endif %}
      {% endwith %}
      <form method="POST" action="/signup">
        <div class="field">
          <div class="control">
            <input class="input is-large" type="email" name="email" placeholder="Email" autofocus="">
          </div>
        </div>
        <div class="field">
          <div class="control">
            <input class="input is-large" type="text" name="name" placeholder="Name" autofocus="">
          </div>
        </div>
        <div class="field">
          <div class="control">
            <input class="input is-large" type="password" name="password" placeholder="Password">
          </div>
        </div>
        <button class="button is-block is-info is-large is-fullwidth">Sign Up</button>
      </form>
    </div>
  </div>
{% endblock %}

services/app/templates/sudoku.html
{% extends "base.html" %}
{% block content %}
  <h6 class="title">Level {{dificulty if dificulty != None else ''}} {{level + 1 if level != None else 'Game Over!! try other levels'}}</h6>
  <div id="sudoku" class="sudoku">
    <table class="sudoku__table" align="center">
      <tbody>
        {%set index = namespace(value=0) %}
        {%set row_class = namespace(value="") %}
        {%set cell_class = namespace(value="") %}
        {% for row in range(1, 10) %}
          {%set row_class.value = "sudoku__table-row " %}
          {%if row % 3 == 0 %}
            {%set row_class.value = row_class.value + "sudoku__table-row--separator" %}
          {%endif%}
          <tr class="{{row_class.value}}">
          {%for cell in range (1, 10) %}
            {%set cell_class.value = "sudoku__table-cell " %}
            {%if cell % 3 == 0 %}
              {%set cell_class.value = cell_class.value + "sudoku__table-cell--separator " %}
            {%endif%}
            {%if sudoku[index.value] != '.'%}
              <td class="{{cell_class.value}}" data-cell-index="{{index.value}}" >
              {{sudoku[index.value]}}
            {%else %}
              {%set cell_class.value = cell_class.value + "sudoku__table-cell--editable" %}
              <td class="{{cell_class.value}}" data-cell-index="{{index.value}}" contenteditable >
              {%if user_game[index.value] != '.'%}
                {{user_game[index.value]}}
              {%endif%}
            {%endif%}
            {%set index.value = index.value + 1%}
            </td>
          {%endfor%}
          </tr>
        {%endfor%}
      </tbody>
    </table>
  </div>
  <script charset="utf-8">
    $(document).ready(function(){
     AddValidations("{{dificulty}}")
   });
  </script>
{% endblock%}